#include "Arduino.cc"
#include "EEPROM.cc"
#include "Redbot.cc"
#include "Serial.cc"
#include "serialHelper.cc"
#include "Spark.cc"
#include "WiFi.cc"
#include "Wire.cc"
#include "SPI.cc"

#include "IRremote.cc"
